include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
      todo: info
      avoid_classes_with_only_static_members: ignore
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    prefer_single_quotes: true
